### ISSUE TITLE
add password change through netlinx code

### ISSUE THREAD

**Issue by nisafronov** [amclain/duet-lib-pjlink#2]
Hello,
Can you add password change functionality through netlinx code. 
I can do it by myself, but have no AXM Cafe Duet to compile java code

Best wishes, Nikita

**Comment by amclain** [comment]
Hi, thanks for your interest in this Duet module.

To the best of my knowledge, the [PJLink specification](http://pjlink.jbmia.or.jp/english/data/5-1_PJLink_eng_20131210.pdf) does not support changing the password of the PJLink device. In my opinion, device passwords should be set up via SSH/Telnet, the device's web interface, or on screen display when the system is commissioned.

**Comment by nisafronov** [comment]
Oh, iam sorry for misunderstand. Your module have variable String _pjlinkPassword = "", method public void setPassword(String password), but no way to change it in netlinx code

**Comment by amclain** [comment]
No problem. The `setPassword` method is for connecting to a PJLink device that requires an authenticated connection. It wasn't exposed to NetLinx because if I remember correctly, Duet doesn't implement the [MD5 digest](https://github.com/amclain/duet-lib-pjlink/blob/35ef92f73cb327a9cd00f033ef48fb021a9e0dde/com/alexmclain/duet/pjlink/dr0_1_2/PJLink.java#L493) required for the authentication procedure.

To use this module, I recommend disabling the authentication on the PJLink device. The system should be secured by placing the master and PJLink device on a dedicated control system network (physical, VLAN, and/or tunnel).
